### ISSUE TITLE
On click event to play certain video in the array

### ISSUE THREAD

**Issue by zaynzafar** [brightcove/videojs-playlist#101]
Like the method **`player.playlist.next()`**, I was wondering if there is a way to play a certain video in the array. Something like `player.playlist.index(2)` --> this should play the second video in the array

Any thoughts? Thanks

**Comment by zaynzafar** [comment]
any help would be appreciated?

**Comment by marguinbc** [comment]
You can use `player.playlist.currentItem(2)` to set the currently playing video to index `2` as documented in the API guide: https://github.com/brightcove/videojs-playlist/blob/master/docs/api.md

**Comment by zaynzafar** [comment]
@marguinbc Thank you, this helped!
