### ISSUE TITLE
Integrating the videojs-dock plugin with the videojs-playlist plugin

### ISSUE THREAD

**Issue by zaynzafar** [brightcove/videojs-playlist#103]
Hi,

I am wondering how I can integrate this dock plugin with the playlist plugin. I have set the name and description of the videos in the playlist array but how can I get it to appear on the dock when you switch videos or go to the next / prev item in the playlist?

Brightcove have done it on their player here:
https://support.brightcove.com/playlist-ui-plugin

Thanks

**Comment by BrandonOCasey** [comment]
I am going to respond in the dock issue that you opened an close this one. Please see: https://github.com/brightcove/videojs-dock/issues/19
