### ISSUE TITLE
4k Mpegdash not playing in playlist

### ISSUE THREAD

**Issue by asadmalik3** [brightcove/videojs-playlist#139]
## Description
Playlist with mpeg dash 4k video is not working in internet explorer. It is working fine in all other browsers.

## Preview
https://angular-videojs-playlist.stackblitz.io

## Stackblitz
https://stackblitz.com/edit/angular-videojs-playlist

## Steps to reproduce
Follow below given steps to reproduce

1. Open https://angular-videojs-playlist.stackblitz.io in internet explorer
2. See video is not being played

### Expected
This should work in internet explorer

### Actual
This is not working in internet exporer

### Error output
No error in console

## Additional Information
If i try to play 4k mpegdash video in video js, it is working fine in internet explorer, but it is not working in playlist mode. This is very strange behavior.

#### videojs
7+

#### browsers
Internet explorer 11

#### OSes
Windows 10

### plugins
https://github.com/brightcove/videojs-playlist

**Comment by misteroneill** [comment]
If there's an issue with playback, it's almost certainly not related to this plugin. Instead, look at the Video.js playback engine, [videojs/http-streaming](https://github.com/videojs/http-streaming).
