### ISSUE TITLE
Version 4.3.0 breaks currentItem() behavior

### ISSUE THREAD

**Issue by jankrueger** [brightcove/videojs-playlist#142]
## Description
I think version 4.3.0 broke the plugins behavior through changes in this feature. 

In the past you could call `player.playlist.currentItem()` before playback has started and receive the initial item index (defaulting to 0). 

With 4.3.0 `currentItem()` will return -1, because it tries to lookup the index by using [`playlist.currentPlaylistItemId_`](https://github.com/brightcove/videojs-playlist/blob/master/src/playlist-maker.js#L348), which is `null` until `playlistitem` has been [triggered](https://github.com/brightcove/videojs-playlist/blob/master/src/playlist-maker.js#L309).

We tried to set `playlist.currentPlaylistItemId_` to the corresponding initial value but ran into with the test cases that have been updated with this feature to handle to changed behavior of `currentItem`. 

Currently the tests only run successful because of lines like [this](https://github.com/brightcove/videojs-playlist/blob/master/test/playlist-maker.test.js#L146) that mimic the behavior when playback was started. 

I think `currentItem` should return a value >= 0 if setup worked correctly but playback hasn't started. 

## Steps to reproduce
Call `player.playlist.currentItem()`before playback has started. This will return -1 although `currentIndex_` is a valid value. 

### Expected
`currentItem()` should return a valid number when called before playback has started.

### Actual
`currentItem()` returns -1 when called before video playback has started.

### plugins
videojs-playlist 4.3.0

**Comment by misteroneill** [comment]
Sounds like a regression. Thanks for reporting it!

**Comment by misteroneill** [comment]
I've changed the `latest` npm dist-tag to point to 4.2.6 until we can get this issue fixed. Version 4.3.0 is now available at `next` on npm.

**Comment by bcdarius** [comment]
@jankrueger `playlist.currentPlaylistItemId_` will indeed be `null` before `playlistitem` is fired. However, it is strange that you see `currentItem()` returning `-1` before playback has begun—`playlistitem` is fired on a player ready at which point `currentPlaylistItemId_` should be set. 

I haven't been able to reproduce this so far—I always get `0` returned by `playlist.currentPlaylistItemId_` prior to playback start. What environment/browser are you seeing this on? A test case would be helpful.

**Comment by jankrueger** [comment]
@bcdarius Thanks for looking into this and creating the test case.
The difference between the previous version and 4.3.0 is that even when calling `currentItem()` before `player.ready()` was fired it would return a correct index (https://jsbin.com/tukavawosu/edit?html,console,output). 
I believe that `brightcove/videojs-playlist-ui` is calling `currentItem` on Component creation and this can happen before `ready` was triggered.

**Comment by bcdarius** [comment]
@jankrueger Thanks for further info. This looks indeed a regression (STR somehow threw me off, it should probably say that calling `player.playlist.currentItem() before player ready—rather than playback start—would return -1). We'll take a look.

**Comment by jankrueger** [comment]
Yes, you are absolutely right about the "read vs. playback" naming. 
On thing that i thought could be worth looking into is the `currentItem` function. In the previous version it used the `currentSrc` of the player to determine the index. That would be helpful if someone had set the players src without using this plugin, right? It would be able to recover state if the source was also in the playlist object. With the new code this wont happen, as it is not using the players src anymore. Why is `currentItem` updating `currentIndex_` before returning it? Should we try to set `currentIndex_` and `currentPlaylistItemId_ ` at the same time?

**Comment by misteroneill** [comment]
Yes, that's correct. We're going to be fixing this soon. Thanks again for bringing it up @jankrueger and sorry for the inconvenience!

**Comment by misteroneill** [comment]
@jankrueger Thanks again for reporting this. If you have some spare time, would you mind taking #145 for a spin? I think it resolves the regression.

**Comment by jankrueger** [comment]
Thanks for the fix! 
Our use cases work as expected.

**Comment by misteroneill** [comment]
Great to hear that @jankrueger - I'll merge the PR and release it right away!

**Comment by misteroneill** [comment]
This should be out in 4.3.1 - I've deprecated 4.3.0
