### ISSUE TITLE
Is there an afterplaylistitem event?

### ISSUE THREAD

**Issue by seabasss** [brightcove/videojs-playlist#165]
I've found `beforeplaylistitem` and `playlistitem`, but is there an `afterplaylistitem` event that fires after the new file is loaded? Or is there a `ready` event in `videojs` that I can use that works every time I switch track? I'm trying to use this with `videojs-markers`, but the markers fire before the trackis loaded and therefor end up in the wrong places when switching track.

Thanks!

**Comment by gkatsev** [comment]
`playlistitem` is the event you're looking for. It fires after we change the source in the player. Is it triggered too early for you? Otherwise, you can potentially listen to `loadedmetadata` which will fire each time a new video has loaded its metadata.

**Comment by seabasss** [comment]
@gkatsev Yes, that's exactly what I ended up doing! Here's the ticket:

```
player.ready(function() {
  player.on('loadedmetadata', function() {//...});
});
```

Thanks!

**Comment by gkatsev** [comment]
You shouldn't need the `player.ready`. If you're listening to `loadedmetadata` inside the `playlistitem` event, then you should use `.one` rather than `.on`, so, you don't keep piling on event handlers. Theoretically, you could do something like:
```js
player.on('loadedmetadata', function() {
  const playlistItem = player.playlist()[player.playlist.currentItem()];
  // do something with the playlist item.
});
```
But either way works, there's no "right" or "wrong" way here.

**Comment by seabasss** [comment]
Cool! I didn't get just `player.on('loadedmetadata', function() {});` to do what I needed outside of the `playlistitem` event, but I removed ready and changed `on` to `one` and it seems to work. Thanks.

**Comment by gkatsev** [comment]
Awesome, glad you got it work.
