### ISSUE TITLE
npm run build exits with error

### ISSUE THREAD

**Issue by pddm** [brightcove/videojs-playlist#17]
Hi, 
npm run build exits the same on 2 different systems Ubuntu an Windows:

npm output:
> videojs-playlist@1.0.3 build /home/patrick/videojs/videojs-playlist-master
> npm run build-dist

> videojs-playlist@1.0.3 build-dist /home/patrick/videojs/videojs-playlist-master
> mkdir -p dist/ && browserify . -s videojs-playlist -o dist/bundle.js && browserify . -s videojs-playlist -p deumdify > dist/global.js

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: EACCES, open 'dist/bundle.js'

npm ERR! Linux 3.16.0-50-generic
npm ERR! argv "node" "/usr/bin/npm" "run" "build-dist"
npm ERR! node v0.10.37
npm ERR! npm  v3.3.4
npm ERR! code ELIFECYCLE
npm ERR! videojs-playlist@1.0.3 build-dist: `mkdir -p dist/ && browserify . -s videojs-playlist -o dist/bundle.js && browserify . -s videojs-playlist -p deumdify > dist/global.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the videojs-playlist@1.0.3 build-dist script 'mkdir -p dist/ && browserify . -s videojs-playlist -o dist/bundle.js && browserify . -s videojs-playlist -p deumdify > dist/global.js'.
npm ERR! This is most likely a problem with the videojs-playlist package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mkdir -p dist/ && browserify . -s videojs-playlist -o dist/bundle.js && browserify . -s videojs-playlist -p deumdify > dist/global.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls videojs-playlist
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/patrick/videojs/videojs-playlist-master/npm-debug.log

npm ERR! Linux 3.16.0-50-generic
npm ERR! argv "node" "/usr/bin/npm" "run" "build"
npm ERR! node v0.10.37
npm ERR! npm  v3.3.4
npm ERR! code ELIFECYCLE
npm ERR! videojs-playlist@1.0.3 build: `npm run build-dist`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the videojs-playlist@1.0.3 build script 'npm run build-dist'.
npm ERR! This is most likely a problem with the videojs-playlist package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build-dist
npm ERR! You can get their info via:
npm ERR!     npm owner ls videojs-playlist
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/patrick/videojs/videojs-playlist-master/npm-debug.log

npm-debug.log:
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@3.3.4
3 info using node@v0.10.37
4 verbose node symlink /usr/bin/node
5 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
6 info lifecycle videojs-playlist@1.0.3~prebuild: videojs-playlist@1.0.3
7 silly lifecycle videojs-playlist@1.0.3~prebuild: no script for prebuild, continuing
8 info lifecycle videojs-playlist@1.0.3~build: videojs-playlist@1.0.3
9 verbose lifecycle videojs-playlist@1.0.3~build: unsafe-perm in lifecycle true
10 verbose lifecycle videojs-playlist@1.0.3~build: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/patrick/videojs/videojs-playlist-master/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin
11 verbose lifecycle videojs-playlist@1.0.3~build: CWD: /home/patrick/videojs/videojs-playlist-master
12 silly lifecycle videojs-playlist@1.0.3~build: Args: [ '-c', 'npm run build-dist' ]
13 silly lifecycle videojs-playlist@1.0.3~build: Returned: code: 1  signal: null
14 info lifecycle videojs-playlist@1.0.3~build: Failed to exec build script
15 verbose stack Error: videojs-playlist@1.0.3 build: `npm run build-dist`
15 verbose stack Exit status 1
15 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:233:16)
15 verbose stack     at EventEmitter.emit (events.js:98:17)
15 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
15 verbose stack     at ChildProcess.emit (events.js:98:17)
15 verbose stack     at maybeClose (child_process.js:766:16)
15 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
16 verbose pkgid videojs-playlist@1.0.3
17 verbose cwd /home/patrick/videojs/videojs-playlist-master
18 error Linux 3.16.0-50-generic
19 error argv "node" "/usr/bin/npm" "run" "build"
20 error node v0.10.37
21 error npm  v3.3.4
22 error code ELIFECYCLE
23 error videojs-playlist@1.0.3 build: `npm run build-dist`
23 error Exit status 1
24 error Failed at the videojs-playlist@1.0.3 build script 'npm run build-dist'.
24 error This is most likely a problem with the videojs-playlist package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     npm run build-dist
24 error You can get their info via:
24 error     npm owner ls videojs-playlist
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]

Thanks

**Comment by thesainthell** [comment]
Hi, almost the same issue here, except i'm on a windows environment:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build-dist' ]
2 info using npm@1.4.28
3 info using node@v0.10.37
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose run-script [ 'prebuild-dist', 'build-dist', 'postbuild-dist' ]
6 info prebuild-dist videojs-playlist@1.0.3
7 info build-dist videojs-playlist@1.0.3
8 verbose unsafe-perm in lifecycle true
9 info videojs-playlist@1.0.3 Failed to exec build-dist script
10 error videojs-playlist@1.0.3 build-dist: `mkdir -p dist/ && browserify . -s videojs-playlist -o dist/bundle.js && browserify . -s videojs-playlist -p deumdify > dist/global.js`
10 error Exit status 1
11 error Failed at the videojs-playlist@1.0.3 build-dist script.
11 error This is most likely a problem with the videojs-playlist package,
11 error not with npm itself.
11 error Tell the author that this fails on your system:
11 error     mkdir -p dist/ && browserify . -s videojs-playlist -o dist/bundle.js && browserify . -s videojs-playlist -p deumdify > dist/global.js
11 error You can get their info via:
11 error     npm owner ls videojs-playlist
11 error There is likely additional logging output above.
12 error System Windows_NT 6.2.9200
13 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build-dist"
14 error cwd D:\Downloads\videojs-playlist-vjs-5-upgrade
15 error node -v v0.10.37
16 error npm -v 1.4.28
17 error code ELIFECYCLE
18 verbose exit [ 1, true ]
```

Any suggestions how to fix this?

**Comment by thesainthell** [comment]
On a UNIX system I could resolve the same issues with installing npm module dependcies first. After "npm install" I succeded with "npm run build-dist". Don't know why this is not working on windows but I guess its because of the phantomjs module (I've struggeld with phantomjs on windows my times).

Maybe it helps someone else.

**Comment by gkatsev** [comment]
I believe the issue with windows is that it doesn't have a `mkdir` command which is used to make sure that the `dist/` folder is created. If you create that folder manually, I wonder whether the command would run.

**Comment by misteroneill** [comment]
The build tooling has been brought up to speed with that offered by [the plugin generator](https://github.com/videojs/generator-videojs-plugin); so, it should be working across platforms now. If not, please file an issue there, thanks!
