### ISSUE TITLE
How to import for use in Angular 9?

### ISSUE THREAD

**Issue by kosso** [brightcove/videojs-playlist#180]
I have a video.js player component working in Angular 9. 
When I import video.js I use: 

`import videojs from 'video.js';`

.. and after that, when I want to add the `videojs-youtube` plugin, I add: 

`import 'videojs-youtube';`

Yet despite after this, adding :

`import 'videojs-playlist';`

.. I do not seem to be able use `this.player.playlist([...])`  as .playlist(..)  is undefined. 

So, what is the correct way to `import` this plugin in Angular?

Thanks.

**Comment by gkatsev** [comment]
I'd expect `import 'videojs-playlist';` to work.
