### ISSUE TITLE
Problems with the 'textTracks' tag

### ISSUE THREAD

**Issue by ghost** [brightcove/videojs-playlist#196]
Could you show an accurate example of how to add 'textTracks' tag inside JavaScript code? I can't find a way to properly add the subtitle within these lines:

sources: [{
    src: 'sample.mp4',
    type: 'video/mp4'
  }],
  poster: 'poster.jpg'
},
textTracks where? and how?

**Comment by gkatsev** [comment]
Here's a more complete example: https://github.com/videojs/videojs.com/blob/main/src/components/HomeComponents/AdvancedExample/playlist.js

You can see a usage of [text tracks in the elephants dream video](https://github.com/videojs/videojs.com/blob/dd63c1616feb00d18fb72d0bfc47cc4a98dae14c/src/components/HomeComponents/AdvancedExample/playlist.js#L100-L164).
