### ISSUE TITLE
How to use with videojs-resolution-switcher?

### ISSUE THREAD

**Issue by MTRNord** [brightcove/videojs-playlist#25]
How can I use this plugin together with the "videojs-resolution-switcher[¹]" plugin? Is this supported?

[¹]https://github.com/mysamimi/videojs-resolution-switcher

**Comment by gkatsev** [comment]
Hi,
Unfortunately, I don't think it's compatible. vjs-resolution-switcher seems to require a user to use `player.updateSrc()`, a new method it adds, for it to function. This plugin only uses `player.src()`.
Thanks.
