### ISSUE TITLE
addRemoteTextTrack - improper context

### ISSUE THREAD

**Issue by simshanith** [brightcove/videojs-playlist#26]
When using remote text tracks, the plugin sometimes throws an error even after player is ready.

https://github.com/brightcove/videojs-playlist/blob/master/src/play-item.js#L39

```js
  (item.textTracks || []).forEach(player.addRemoteTextTrack);
```

...should be...

```js
  (item.textTracks || []).forEach(player.addRemoteTextTrack.bind(player));
```

...or similar.

I can open a PR or leave it up to you. Worked around by binding addRemoteTextTrack to my player instance before initializing, e.g.

```js
var player = videojs('myvideo');
player.addRemoteTextTrack = player.addRemoteTextTrack.bind(player);
player.playlist(opts);
```

**Comment by gkatsev** [comment]
Yep, you're right. Can you submit a PR? That would be awesome.
