### ISSUE TITLE
Package isn't installable via bower

### ISSUE THREAD

**Issue by natecox** [brightcove/videojs-playlist#32]
So I've been trying to use this package for a bit now, and I've come to realize that the bower package I installed doesn't actually reference this repo, instead it references https://github.com/jgallen23/videojs-playLists

Doing a search for this package as referenced in the documentation doesn't get me any result:

    > bower install videojs-playlist                                                                                                             
    bower                        ENOTFOUND Package videojs-playlist not found

And searching for brightcove doesn't get me any relevant results either: 

    > bower search brightcove                                                                                                                    
    Search results:
    
        videojs-errors git://github.com/brightcove/videojs-errors
        jquery-brightcove git://github.com/KanbanSolutions/jquery-brightcove.git
        videojs-thumbnails git://github.com/brightcove/videojs-thumbnails.git
        pkcs7 git://github.com/brightcove/pkcs7.git

**Comment by aiyuchen** [comment]
the same to u

**Comment by misteroneill** [comment]
This is an older issue, but it would be useful to try again. There have been a number of conventional changes to this plugin since January. It might work now. Either way, we have no control over how Bower searches GitHub since it has no registry like a real package manager.

**Comment by simshanith** [comment]
Bower does have a registry... http://bower.io/docs/creating-packages/#register

**Comment by natecox** [comment]
Not sure why this was closed. Bower absolutely has a registry as indicated above, and the package still is not installable via bower as indicated in the readme.

**Comment by natecox** [comment]
All that really needs to happen here is this package's `bower.json` needs to be updated and have this repo location added to it, and then be registered.

**Comment by gkatsev** [comment]
Registered:
```sh
$ bower info videojs-playlist
bower not-cached    https://github.com/brightcove/videojs-playlist.git#*
bower resolve       https://github.com/brightcove/videojs-playlist.git#*
bower checkout      videojs-playlist#v2.4.0
bower invalid-meta  The "main" field cannot contain minified files
bower mismatch      Version declared in the json (2.0.0) is different than the resolved one (2.4.0)
bower resolved      https://github.com/brightcove/videojs-playlist.git#2.4.0

{
  name: 'videojs-playlist',
  version: '2.4.0',
  author: 'Brightcove, Inc.',
  license: 'Apache-2.0',
  main: [
    'dist/videojs-playlist.min.js'
  ],
  keywords: [
    'videojs',
    'videojs-plugin'
  ],
  homepage: 'https://github.com/brightcove/videojs-playlist'
}

Available versions:
  - 2.4.0
  - 2.3.1
  - 2.3.0
  - 2.2.0
  - 2.1.0
  - 2.0.0
  - 1.0.3
  - 1.0.2
  - 1.0.1
  - 1.0.0

You can request info for a specific version with 'bower info videojs-playlist#<version>'
```

**Comment by gkatsev** [comment]
If someone wants to fix the version field in the bower.json (by just removing it altogether, it's unnecessary) we'll accept that PR.
Also, apparently, I forgot to push the 2.4.1 tag when I last versioned this.

**Comment by misteroneill** [comment]
@simshanith Thanks for clarifying! I guess Bower has upped their game since I last used it. 👍

**Comment by gkatsev** [comment]
It's been registered.
