### ISSUE TITLE
How can I go to  Specified video

### ISSUE THREAD

**Issue by aiyuchen** [brightcove/videojs-playlist#34]
if current play first video，How can I go to the fifth video

**Comment by gkatsev** [comment]
You can use `player.playlist()` to get the list of videos and then get the 5th item using standard array operations.
```js
var list = player.playlist();
var fith = list[4];
```
Hope that helps, thanks.

**Comment by aiyuchen** [comment]
I use this
```
player.playlist.currentItem(0);
player.playlist.currentItem(4);
```

**Comment by gkatsev** [comment]
sorry, I completely misread the question. `player.playlist.currentItem` is the correct approach as written in the [API docs](https://github.com/brightcove/videojs-playlist/blob/master/docs/api.md#playerplaylistcurrentitemnumber-index---number).
