### ISSUE TITLE
hmmm is that bug?

### ISSUE THREAD

**Issue by FndNur1Labs** [brightcove/videojs-playlist#35]
I not sure but not like you tube expected hope fixed again thank you.

the button not in video @_@

![playlist](https://cloud.githubusercontent.com/assets/11433397/13721758/46ae62de-e863-11e5-8752-7e9acd3e5752.png)

**Comment by misteroneill** [comment]
This is not a bug. The videojs-playlist plugin does not provide the UI for playlists. For that you want to also use videojs-playlist-ui. However, its controls are also not in the player.
