### ISSUE TITLE
Using plugin with browserify.

### ISSUE THREAD

**Issue by alexchern** [brightcove/videojs-playlist#36]
Hi there,

How can I use this plugin with browserify? 
I tried
```
var videojs = require('video.js');
videojs.plugin('playlist', require('videojs-playlist'));

```
or 

`var videojs = require('video.js'); 
videojs.registerComponent('playlist', require('videojs-playlist'));
`

with no luck....

plugin.js:27 Uncaught TypeError: Cannot read property 'plugin' of undefined

Thanks,

Alex

**Comment by alexchern** [comment]
Well,

Here is a workaround (as suggested by Gary Katsevman):

```
var videojs = require('video.js');
window.videojs = videojs;
videojs.plugin('playlist', require('videojs-playlist'));
```

Alex

**Comment by gkatsev** [comment]
Heh, cool, yeah, we need to fix that here as well.
Also, you should be able to just call `require('videojs-playlist')`, it will register itself for you.

**Comment by AlexLi88** [comment]
Hi there, 
I tried to require('videojs-playlist') but it still give me an error "Uncaught TypeError: Cannot read property 'plugin' of undefined." 
But if I registered videojs under window object it works like a magic.  Can you explain why i have to use window object?   
Thanks

**Comment by woodcipher** [comment]
Good morning,
I've tried the following:

```javascript
import 'videojs-contrib-hls';
import videojs from 'video.js'
require('videojs-playlist');
```

And:

```javascript
import 'videojs-contrib-hls';
import videojs from 'video.js'
if (typeof window !== 'undefined') {
  window.videojs = videojs;
}
require('videojs-playlist');
```

Either way, I still get this error when trying to set a playlist:
```
Uncaught TypeError: player.playlist is not a function
```
Any ideas? Any help would be greatly appreciated! Thank you.

**Comment by wiscat** [comment]
@woodcipher 
```
import videojs from 'video.js';
import videojsPlaylistPlugin from 'videojs-playlist';
videojs.registerPlugin('playlist', videojsPlaylistPlugin);
```
worked for 
```
"video.js": "~7.0.3",
"videojs-playlist": "~4.2.1"
```
