### ISSUE TITLE
Requirejs : define videojs-playlist return undefined

### ISSUE THREAD

**Issue by br3aking-bad** [brightcove/videojs-playlist#39]
Hello,

I am using requirejs to import videojs-playlist, but when I do it, the type returned by requirejs  is undefined instead of a function. 

Part of my code : 

**loadplaylist.js**
```
define(["jquery",'mod_playlist/jsrender',"mod_playlist/video"], function($,jsrender,videojs) {
var t;
 t = {
     init : function( param1) {
          require(['mod_playlist/videojs-playlist'], function(videojsplaylist) {
....
....
```

I add the following line at the beginning of my videojs-playlist.js

` define(["mod_playlist/video"], function(videojs) {
`

Videojs work well, I can use it, and the type of the object videojs is a function, in addition it seems to me that there is no circular dependencies. Do you have an idea how to solve this problem ?

**Comment by br3aking-bad** [comment]
I finnally decided to use browserify to handle dependencies and it work fine now.

**Comment by gkatsev** [comment]
Thanks for checking back in.
I have a feeling that the requirejs issue is similar to our other browserify issue where we expect videojs to be loaded in globally rather than via a dependency.

**Comment by gkatsev** [comment]
But even better than you got it working with browserify :)

**Comment by br3aking-bad** [comment]
The good point is that I have a big javascript file that is like a "standalone", and it's a lot easier to manage in my current project with moodle !
