### ISSUE TITLE
Browserify : can't compile, Cannot find module

### ISSUE THREAD

**Issue by br3aking-bad** [brightcove/videojs-playlist#40]
I made a script for browserify, but when I tried to compile the script it give me errors :  

I installed videojs-playlist with  npm install videojs-playlist.

Then I decided to compile my script solution.js that contain : 
```
window.$ = window.jQuery = require('./jquery');
window.videojs = require('./video');
window.videojsplaylist=require('./node_modules/videojs-playlist/dist/videojs-playlist.js');

var player = videojs('video');

```

But it gives me : 
```
`Error: Cannot find module './auto-advance.js' from 'C:\test\node_modules\videojs-playlist\dist'
etc ...
```

So I decided to move  all files from videojs-playlist\src to ideojs-playlist\dist but I feel that I am doing it wrong because in the documentation of videojs-playlist, it is written that it should work out of the box. And even if I move files I got errors : 

```
$ browserify solution.js -o solution.dist.js
Error: Cannot find module './hasSymbols' from 'C:\test\node_modules\videojs-playlist\dist'
    at C:\Users\1601067\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:55:21
    at load (C:\Users\1601067\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\Users\1601067\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:92:31)
    at C:\Users\1601067\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)

```

Thank you for your attention.

**Comment by gkatsev** [comment]
Why not just `require('videojs-playlist')`? You shouldn't need to specifically require the dist file.

**Comment by br3aking-bad** [comment]
I don't know why but if I write : 

`require('videojs-playlist')
`

instead of 

`require('videojsplaylist')
`

I would have a parsing file error, maybe due to the "-" character.

```
$ browserify solution.js -o solution.dist.js
Error: Parsing file C:\test\solution.js: Assigning to rvalue (3:0)
```

So should I  write this ?

`window.videojsplaylist=require('./node_modules/videojs-playlist');
`

Now browserify can't find the browserify-shim : 

```
$ browserify solution.js -o solution.dist.js
Error: Cannot find module 'browserify-shim' from 'C:\test\node_modules\videojs-playlist'

```

**Comment by gkatsev** [comment]
the name of the module is `videojs-playlist`, so, you have to require it with `require('videojs-playlist')`.
We do have an issue where videojs-playlist expects videojs to be global (see #36), so, you'd need to do something like:
```js
var videojs = require('video.js');
window.videojs = videojs;
require('videojs-playlist');
```

**Comment by br3aking-bad** [comment]
Ok nice ! It solved the problem to find the module, and for the missing browserify-shim I just entered this line in the prompt` npm install browserify-shim`. Thank you for the fast replies.

**Comment by gkatsev** [comment]
np, I guess fixing #36 will fix this issue as well, so, I'm going to close this.
