### ISSUE TITLE
Captions/Subtitles support?

### ISSUE THREAD

**Issue by fmp777** [brightcove/videojs-playlist#47]
I tried adding a captions array after the "sources" but didn't seem to take.  Any support for this?

**Comment by gkatsev** [comment]
We should document it, but it's a [`textTracks` property](https://github.com/brightcove/videojs-playlist/blob/master/src/play-item.js#L55). An array with objects that looks like the the one that [`Player#addRemoteTextTracks`](https://github.com/videojs/video.js/blob/master/docs/guides/text-tracks.md#playeraddremotetexttrackobject-options---htmltrackelement) accepts.

**Comment by fmp777** [comment]
Yea I just stumbled into that while reviewing the code.  

`"textTracks":[
				{
					"kind":"captions",
					"label":"French",
					"src":"/path/to/webvtt",
					"default":false
				}
]`

Thanks!

**Comment by gkatsev** [comment]
Np.

**Comment by haietza** [comment]
@gkatsev After I call player.src to add the source for the selected playlist video, I'm calling player.addRemoteTextTrack() to add the captions file for that video, but it does not appear to be working:

player.src([                
  { type: "rtmp/mp4", src:  src },
  { type: "video/mp4", src:  mp4i }
]);
var trackOptions = new Object();
trackOptions.kind = 'captions';
trackOptions.mode = 'showing';
trackOptions.label = 'english';
trackOptions.srclang = 'en';
trackOptions.default = 'true';
trackOptions.src = 'captionsrc';
player.addRemoteTextTrack(trackOptions);

Do you have a code example of how to use the addRemoteTextTrack function you could share? Thank you again!
