### ISSUE TITLE
`data-setup` Documentation?

### ISSUE THREAD

**Issue by robmoggach** [brightcove/videojs-playlist#49]
Previously we were able to setup playlists with videojs using and html5 tag video tag attribute:

```
data-setup='{
    "playlist" : [ 
        {   
            "thumb_url" : "{{ videothumb.url }}"
            "poster_url" : "{{ videoposter.url }}",
            "sources" : [ 
                {
                    "src" : "{{ source.file.url }}",
                    "type" : "{{ source.get_type }}",
                    "media" : "",
                    "title" : ""
                },
            ]
        },
    ]
```

Does this still work with this now standalone plugin and is the syntax the same?

Are there plans to document this better or implement it?

**Comment by simshanith** [comment]
This is a core VideoJS feature - I'd be surprised if it no longer works.

I agree it could be better documented for the plugin-specific options here

http://docs.videojs.com/docs/guides/options.html

**Comment by robmoggach** [comment]
Ha! Better than no documentation at all? 

This works...

    <script type="text/javascript">
    $(document).ready(function() {
        var setup=$('#playlist').data('setup');
        var pl_player=videojs('playlist');
        pl_player.playlist(setup.playlist);
        pl_player.playlistUi();
    });
    </script>

It'd be great to see per source `techOrder` so we can mix and match vimeo, youtube, and html5 video in a playlist - 

Leaving this open as documentation is needed.

**Comment by Strap1** [comment]
@robmoggach Would you mind sharing some of your final code? I have a setup very similar to yours with a playlist consisting of only YouTube videos. I'm using data-seup for my playlist object and then initialising in JS. Something like this:

`"playlist": [{
	"name": "Adam & Bones – Harry’s Bar",
	"description": "",
	"sources": {
		"src": "https://www.youtube.com/watch?v=FIxJKCCbPDE",
		"type": "video/youtube"
	},
	"thumbnail": {
		"src": "/hhie/wp-content/uploads/2014/05/Adam-Bones-Dont-Move.jpg"
	}
}, {
	"name": "Adam & Cuth – Life Goes On",
	"description": "",
	"sources": {
		"src": "https://www.youtube.com/watch?v=VZeZPL42oXA",
		"type": "video/youtube"
	},
	"thumbnail": {
		"src": "/hhie/wp-content/uploads/2013/02/Adam-Cuth.png"
	}
}]`

and my JS

`var options = { "techOrder": ["youtube"] };
var setup = $('#hhie-playlist-player').data('setup');
//console.log(setup);
var player = videojs('hhie-playlist-player', options);
player.playlist(setup.playlist);
player.playlistUi();`

I'm getting this error:
`VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media`

Any help much appreciated.
