### ISSUE TITLE
currentItem() === -1 when a new playlist is loaded

### ISSUE THREAD

**Issue by dmlap** [brightcove/videojs-playlist#5]
It should be zero, right?

**Comment by gkatsev** [comment]
Yep, a bug in my fix of my fix.

**Comment by forbesjo** [comment]
Closed by 8ba06a41e179b0d91f448492f67abcf35f22c4e9

**Comment by gkatsev** [comment]
Believe it's fixed.

**Comment by pipechaves** [comment]
still have the issue. so to load the new list is just to do


player.playlist([

"add playlist here"

]);

right??

If so I still have the -1 issue
