### ISSUE TITLE
Autoadvance(0) does not start the playback of  the videos ?

### ISSUE THREAD

**Issue by rodofatos** [brightcove/videojs-playlist#53]
Hello, i am trying to use the playlist plugin but seems i'm doing something wrong because after i give the source playlist and set autoadvance to 0 nothing happens with the player. 

```javascript
this.player = videojs('video-widget-player');
var playlist = [];
for (var i = 0; i < videoItems.length; i++) {
    playlist.push({
        sources: [
            {
                src: 'http://localhost:45398/Content/videos/' + videoItems[i] + '.mp4',
                type: 'video/mp4'
            }
        ]
    });
}
this.player.playlist(playlist);
this.player.playlist.autoadvance(0);
`

**Comment by gkatsev** [comment]
That's right. If the player is not already playing, `autoadvance(0)` will not play it for you. [autoadvance](https://github.com/brightcove/videojs-playlist/blob/master/docs/api.md#playerplaylistautoadvancenumber-delay---undefined) only sets up the autoadvance behavior for the playlist. If you want the player to start playing, you should call `player.play()`.

Hope that helps.

**Comment by rodofatos** [comment]
Still in this way the videos are not 'autoadvanced' and the `player.playlist.currentItem()` is set to -1 whenever a video ends. Also its not playing next video.

Is something wrong with what i am doing ?
