### ISSUE TITLE
infinite loop when playlist item, have duplicate filename

### ISSUE THREAD

**Issue by mpowroznik** [brightcove/videojs-playlist#57]
Hi.

I have problem with playlist. When I set files with names
file1.mp4
file2.mp4
file1.mp4
file3.mp4
file1.mp4

Player just play
file1.mp4
file2.mp4
file1.mp4
file2.mp4

etc...

even when I check with player.playlist.currentItem() I get  0,1,0,1,0,1 etc...

**Comment by PaulGregor** [comment]
Same problem here

**Comment by espaciosti** [comment]
I have the same issue with the playlist, someone have a solution ?

**Comment by ingmferrer** [comment]
I'm having this same problem.
