### ISSUE TITLE
URL with spaces won't autoadvance

### ISSUE THREAD

**Issue by maddygoround** [brightcove/videojs-playlist#59]
If user provide series of URL which content spaces in between the name then auto-advance feature will break.

A simple reason to this is 
` playlist.currentIndex_ = playlist.indexOf(playlist.player_.currentSrc() || '');`

will not be able to match the URL against the URL's that are inside the array of playlist as the `playlist.player_.currentSrc()` will be encoded-URL.

To solve this issue i simply change the above line to
 `playlist.currentIndex_ = playlist.indexOf(decodeURI(playlist.player_.currentSrc() || ''));`

Let me know your thoughts.

**Comment by leggomuhgreggo** [comment]
Here's work around, in case it's helpful for others:

```
player.on("ended", function() {
  player.playlist.next()
});
```
