### ISSUE TITLE
playlistitem firing before switching item?

### ISSUE THREAD

**Issue by diniscorreia** [brightcove/videojs-playlist#62]
I'm trying to use `currentItem()` when the `playlistitem` event is fired - however, I always get the index of the previous item and not the one I'm switching to. 

You can see the problem on the working example. Binding the event before loading the playlist...

`player.on('playlistitem', function(){
  console.log( player.playlist.currentItem() );
});`

... will output 0 when the playlist loads and 0 again if you click the Next button.

**Comment by mlumbroso** [comment]
As a (ugly) workaround, I just setTimeout 500ms after the event before using the currentItem() function.

**Comment by nfepl** [comment]
I'm having the same issue.
On desktop it works fine always.
On mobile, if I set a breakpoint and inspect whenever the event is triggered, the currentItem() function returns the correct value (updated one). But if no breakpoint is set, outputting to console, that same method returns the previous value.
