### ISSUE TITLE
How to define captions for each video in a playlist?  

### ISSUE THREAD

**Issue by oshihirii** [brightcove/videojs-playlist#64]
Can it be added to the playlist object? 

If so, can someone please tell me correct syntax/format to use?

```
{
    name: 'Video Title',
    description: 'Description goes here',
    duration: 45,
    sources: [
        { src: 'http://vjs.zencdn.net/v/oceans.mp4', type: 'video/mp4' },
        { src: 'http://vjs.zencdn.net/v/oceans.webm', type: 'video/webm' },
    ],
    poster: 'oceans.jpg',
    // you can use <picture> syntax to display responsive images
    thumbnail: [{
        srcset: 'oceans.jpg',
        type: 'image/jpeg',
        media: '(min-width: 400px;)'
    }, {
        src: 'oceans-low.jpg'
    }]
}
```

**Comment by oshihirii** [comment]
Oh, actually, answer might be here, I will test!

https://github.com/brightcove/videojs-playlist/issues/47

**Comment by oshihirii** [comment]
Hmm, am getting this warning in console:

> VIDEOJS: WARN: Calling addRemoteTextTrack without explicitly setting the "manualCleanup" parameter to `true` is deprecated and default to `false` in future version of video.js

And am trying to test with a local vtt file (it normally works in Firefox), and a vtt file hosted on `localhost` (in Chrome) but getting:

> XMLHttpRequest cannot load http://localhost/static/img/videos/captions.en.vtt. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.

**Comment by bigt11** [comment]
I just ran across the manualCleanup warning.  I am using the function  addRemoteTextTrack().  

I am adding tracks via js and not a playlist though.  but in the  example below, the ", false" that is outside the {} addresses the "manualCleanup" warning.  You can choose true or false.   here is the notes in the code that i found about manualcleanup

notes about manualCleanup
  ```
/**
   * Create a remote {@link TextTrack} and an {@link HTMLTrackElement}. It will
   * automatically removed from the video element whenever the source changes, unless
   * manualCleanup is set to false.
   *
   * @param {Object} options
   *        Options to pass to {@link HTMLTrackElement} during creation. See
   *        {@link HTMLTrackElement} for object properties that you should use.
   *
   * @param {boolean} [manualCleanup=true] if set to false, the TextTrack will be
   *
   * @return {HTMLTrackElement}
   *         the HTMLTrackElement that was created and added
   *         to the HTMLTrackElementList and the remote
   *         TextTrackList
   *
   * @deprecated The default value of the "manualCleanup" parameter will default
   *             to "false" in upcoming versions of Video.js
   */
```

How I made manualCleanup happy, at least seems to work for now.
`currentPlayer.addRemoteTextTrack({ src: 'scripts/videojs/tracks/captions/captionsFile.vtt', kind: 'captions', srclang: 'en', label: 'English'}, false);`
