### ISSUE TITLE
RTMP support

### ISSUE THREAD

**Issue by haietza** [brightcove/videojs-playlist#72]
Does video-js playlist support RTMP?

**Comment by gkatsev** [comment]
videojs-playlist doesn't play anything itself. It passes the sources to videojs. If videojs is set up to be able to play RTMP (that is, if you have the flash tech available), it should work.

Hope that helps.

**Comment by haietza** [comment]
@gkatsev I think I have it configured so the video code is set up to be able to play RTMP, but the playlist links are still not working - they give "The media could not be loaded, either because the server or network failed or because the format is not supported." error. Would you please mind looking at my code and letting me know what I need to change to get the playlist part working with the player part? I would REALLY appreciate any help: http://www.appstate.edu/~meltonml/videojs-playlist-master/rtmp.html

I appreciate you being so responsive and providing support and direction - it's been very helpful. We use Moodle in conjunction with a Wowza streaming server, and I'm trying to get the integration working for that, so it's a bit of a learning curve :).

**Comment by gkatsev** [comment]
Looks like the playlist plugin you're using isn't this plugin. Not sure how the other one works.

Happy to help.

**Comment by haietza** [comment]
@gkatsev Oh geez - I'm so sorry. I thought I was using this repo for the playlist. Do you guys have an example where the video links for use in the play list are contained in the HTML instead of the javascript file? Or does this implementation require that they be in the JS? Thanks again for all the help!

**Comment by gkatsev** [comment]
You're welcome.

No, this plugin requires that it be in a javascript array that looks somewhat like [this](https://github.com/brightcove/videojs-playlist#basic-usage).
