### ISSUE TITLE
player.playlist.currentItem(); always returns -1

### ISSUE THREAD

**Issue by mendiomon** [brightcove/videojs-playlist#75]
player.playlist.currentItem(); always returns -1

I can get id of current playing video using player.playlist.currentIndex_ - this is hovewer undocumented, i discovered this property using chrome console.

**Comment by gkatsev** [comment]
Propreties that are prefixed and suffixed with an `_`, by convention, are considered private, which is why it isn't documented.
`player.playlist.currentItem()` always returning `-1` sounds like a bug but I'm unable to reproduce it locally. Can you provide a reduced test case, please?

**Comment by peter-gribanov** [comment]
Reproduce bug:

```js
var el = $('#video-player')
var player = videojs(el[0]);

player.playlist(el.data('playlist'));
player.playlist.currentItem(el.data('playlist-item'));
player.playlist.autoadvance(2);

player.on('play', function () {
    console.log(this.currentSrc());
    console.log(player.playlist.indexOf(this.currentSrc()));
    console.log(player.playlist.currentItem());
});
```

Start play:

```
foo.mp4
0
0
```

Change time of playing video:

```
foo.mp4
0
0
```

Start play next video in playlist:

```
foo.mp4
0
0
```

Change time of playing video:

```
bar.mp4
1
1
```

**Comment by peter-gribanov** [comment]
Solution: need use `playing` event.
Sorry for this.

**Comment by dargre** [comment]
I've noticed that currentItem returns "-1" always when video src is relative path. Can't src url be relative?

**Comment by gkatsev** [comment]
@dargre it's possible that this is happening because the src on the video element ends up being resolved to an absolute path but we're checking against a relative path and thus the check fails. This is most likely a bug.

**Comment by mlumbroso** [comment]
FYI, this also happens in case you put a wrong type in the source (for example setting "type": ".mp4") would trigger this error
