### ISSUE TITLE
Feature? Is it possible to inject different source for a particular playlist item before playback?

### ISSUE THREAD

**Issue by jfrux** [brightcove/videojs-playlist#78]
Use case is, we are keeping track of how many videos have played so far and then we want to swap out the source with a special version of the same url, except with ads stitched in it.

I thought maybe `player.on("playlistitem",() => { player.src(<new_source_url) });` but that didn't do it.

**Comment by joshuairl** [comment]
Well, I ended up rigging it up by resetting the playlist whenever an ad needs played.
This just requires a lot more juggling of the playlist since if you change the source of the current item it'll cause the playlist to empty / reset and crap out.
