### ISSUE TITLE
New Feature: Add prev/next buttons to the controlbar optionally

### ISSUE THREAD

**Issue by jienco** [brightcove/videojs-playlist#80]
Hi, first I must say that this plugin is great and works very good.

I was thinking that it would be good to have prev/next buttons on the player controlbar (something like the previous button before the play/pause one, and the next button after it).

So in a single page application for example, it would be possible to reset and change the player source (to single item or to a playlist using the plugin way to load the sources), and the prev/next buttons would be added/removed dynamically (depending if using a single item or playlist).

Also there could be a setup option that would enable the dynamic adding of these controls, making the feature optional.

I know that there is the videojs-playlist-ui project, however I think that one is more related to the external UI to control the playlist, and the prev/next buttons would be part of the core playlist plugin.

What do you think about it? I would also like to contribute if you consider that this feature would be good to be added.

Thanks very much!

**Comment by Markomas** [comment]
Well not best soliution, thats how I use it:

`var videoJsButtonClass = videojs.getComponent('Button');
    var nextPlaylistItem = videojs.extend(videoJsButtonClass, {
      constructor: function() {
        videoJsButtonClass.call(this, player);
        this.addClass('vjs-icon-next-item');
        this.controlText("Next");
      },

      handleClick: function(){
        player.playlist.next();
      }
    });
    player.controlBar.addChild(new nextPlaylistItem(), {}, 1);

    var previousPlaylistItem = videojs.extend(videoJsButtonClass, {
      constructor: function() {
        videoJsButtonClass.call(this, player);
        this.addClass('vjs-icon-previous-item');
        this.controlText("Previous");
      },

      handleClick: function(){
        player.playlist.previous();
      }
    });
    player.controlBar.addChild(new previousPlaylistItem(), {}, 0);`
