### ISSUE TITLE
Seamless transition between video via preloading

### ISSUE THREAD

**Issue by frs17** [brightcove/videojs-playlist#82]
I am creating an app which plays a playlist of videos that are not on my server. Between each video the loading spinner is briefly shown. I would like each video to play one after another seamlessly. Is it possible to preload the next video?

**Comment by joshuairl** [comment]
Anybody happen to know of a solution to this that feels right? :D

**Comment by interprogs** [comment]
Hi,
I'm facing the same issue , with local video  between each video the loading spinner is briefly shown.
Do you have any news about that please ?

**Comment by fschwahn** [comment]
@misteroneill could you explain why this was closed? Is this already solved, or out of scope? I see there was a release the day this was closed, but the changelog doesn't include any mention of preloading, so it may just be a coincidence.

**Comment by BrainCrumbz** [comment]
@fschwahn and other readers, please have a look a little bit above the close notice. There's an open (as of today) Pull Request going on related to this issue: #112

**Comment by tulkas85** [comment]
yes but is not merged in original project, maybe is it still incomplete?

**Comment by goatandsheep** [comment]
Not to my knowledge. Even if I fix tests nobody will merge
