### ISSUE TITLE
Error: plugin "playlist" does not exist

### ISSUE THREAD

**Issue by byarchil** [brightcove/videojs-playlist#83]
**It happened after I updated the videojs and the playlist version**
Test Chrome and Mozilla last version.

**VideoJs Version =** "video.js": "^6.2.7",
**PlayList Version =** "videojs-playlist": "4.0.0",
**Build =** WebPack
 **"npm": "^5.0.3",**
**webpack@2.7.0** 

```
Options 

 autoplay: true,
          controls: true,
          preload: 'auto',
          fluid: false,
          muted: false,
          width: '100%',
          height: '360',
          language: 'en',
          controlBar: {
            remainingTimeDisplay: false,
            playToggle: {},
            progressControl: {},
            fullscreenToggle: {},
            volumeMenuButton: {
              inline: false,
              vertical: true
            }
          },
          techOrder: ['html5'],
          plugins: {
            playlist: {
              autoadvance: true
            }
          }

```

**Error Message** 

` Error in mounted hook: "Error: plugin "playlist" does not exist"
`

**Comment by mdwisuta** [comment]
I got same error, how to configure the videojs-playlist on webpack??

**Comment by gkatsev** [comment]
I think it's because videojs-playlist still depends just on vjs 5.x. We forgot to update it, I'll make a PR.

**Comment by gkatsev** [comment]
Please try version 4.0.1.

**Comment by min1max** [comment]
Same here. Error still exists in version 4.0.1.

**Comment by aschwtzr** [comment]
Is this still an issue in 4.2.0? Having an issue setting this up in Vue.

**Comment by jezperp** [comment]
did someone solve this? having the same error... both "playlist" and "slides" are not working, "hotkeys" are working though but a look at the code tells me these plugins are written completely different

**Comment by MrWiLofDoom** [comment]
I got this error after configuring webpack to work with HLS (https://github.com/videojs/videojs-contrib-hls/issues/600#issuecomment-258400412)

It was working before I implemented HLS and I'm guessing it has something to do with having to bind the videojs to window.
