### ISSUE TITLE
add a playitemchange event

### ISSUE THREAD

**Issue by forbesjo** [brightcove/videojs-playlist#9]
I think it would be useful to have an event that indicates that a new playitem has been fully loaded.

**Comment by gkatsev** [comment]
Wouldn't a `loadstart` or `loadedmetadata` do that?

**Comment by forbesjo** [comment]
Would it be possible to have multiple loadstart/loadedmetadata events fire if you change sources within a  playitem? If that's not a valid or common use case then disregard this issue.

**Comment by gkatsev** [comment]
The sources within a single playlist item shouldn't just change on you, so, you should only get one of these events per item.
