### ISSUE TITLE
CDN Alternative?

### ISSUE THREAD

**Issue by blundercode** [brightcove/videojs-playlist#90]
**Sorry if this is not the correct place for this, please remove at your discretion.** 

Any chance of a CDN alternative to this plugin?

Or an example of the current state of the project inside of a [Plnkr](https://plnkr.co/) or [Codepen](https://codepen.io/)?

If possible both of those would be greatly appreciated and would definitely help with adoption.

**Comment by gkatsev** [comment]
We don't have it documented, but it is available on jsdeliver and unpkg.
https://www.jsdelivr.com/package/npm/videojs-playlist
https://unpkg.com/videojs-playlist/dist/

Want to submit a PR to add a section in the README with those two links?
